
CREATE TABLE "Hotel" (
	"RoomID"	INTEGER NOT NULL UNIQUE,
	"RoomNumber"	INTEGER NOT NULL UNIQUE,
	"BasePrice"	INTEGER NOT NULL,
	"RoomType"	TEXT NOT NULL,
	PRIMARY KEY("RoomID")
);
CREATE TABLE "Guest" (
	"GuestID"	INTEGER NOT NULL UNIQUE,
	"FirstName"	TEXT NOT NULL,
	"LastName"	TEXT NOT NULL,
	"Email"	TEXT NOT NULL,
	PRIMARY KEY("GuestID")
);
CREATE TABLE "Reservation" (
	"ResrvationID"	INTEGER NOT NULL UNIQUE,
	"GuestID"	INTEGER NOT NULL,
	"RoomID"	INTEGER NOT NULL,
	"DaysStay"	INTEGER NOT NULL DEFAULT 1,
	"StartDate"	TEXT NOT NULL,
	"DateCreated"	TEXT NOT NULL,
	"PaidStatus"	TEXT NOT NULL,
	"ReservationStatus"	TEXT NOT NULL,
	"ConfirmStatus"	INTEGER NOT NULL,
	"TotalCost"	NUMERIC NOT NULL,
	PRIMARY KEY("ResrvationID")
);
INSERT INTO "Guest" ("GuestID","FirstName","LastName","Email") VALUES (1,'Charles','Eaton','semper.rutrum.Fusce@consectetuerrhoncusNullam.co.uk'),
 (2,'Brenda','Larson','Cras@aultricies.net'),
 (3,'Kaden','Freeman','a.auctor@et.net'),
 (4,'Kato','Branch','felis@augueidante.org'),
 (5,'Regan','Cohen','amet.consectetuer@sedturpis.edu'),
 (6,'Gavin','Gilmore','In.ornare@eratSed.co.uk'),
 (7,'Grant','Hutchinson','sem.molestie.sodales@gravidasitamet.org'),
 (8,'Lester','Phelps','eget@euismodet.edu'),
 (9,'Natalie','Mcdowell','habitant.morbi@ac.net'),
 (10,'Germaine','Stout','Donec.dignissim@vitaesodales.com'),
 (11,'Zenaida','Mcmillan','Pellentesque.ultricies@massalobortis.org'),
 (12,'Ethan','Beard','elit.pharetra.ut@dictumaugue.net'),
 (13,'Lareina','Fischer','libero@eu.net'),
 (14,'Kevin','Deleon','vel.arcu.Curabitur@Suspendissealiquet.co.uk'),
 (15,'Cade','Lynch','senectus.et.netus@sit.ca'),
 (16,'Dean','Montoya','gravida.Praesent@Suspendissesagittis.net'),
 (17,'Clare','Hurley','dui@dictumplacerataugue.ca'),
 (18,'Sybil','House','faucibus.leo.in@DuisgravidaPraesent.net'),
 (19,'Salvador','Nolan','mi.tempor@afeugiat.co.uk'),
 (20,'Raja','Conley','ornare@parturientmontesnascetur.co.uk'),
 (21,'Sybil','Rivers','commodo.tincidunt@scelerisqueneque.com'),
 (22,'Grant','Coffey','aliquet.odio@musProin.org'),
 (23,'Vaughan','Pate','semper@et.co.uk'),
 (24,'Bethany','Dyer','amet.ante.Vivamus@egetmollis.net'),
 (25,'Destiny','Peters','Duis@Aeneanegetmagna.org'),
 (26,'Tasha','Ferrell','et.ultrices.posuere@sitamet.co.uk'),
 (27,'Kermit','Boyle','est.vitae.sodales@sedhendrerit.co.uk'),
 (28,'Aurelia','Church','id.magna@Crasloremlorem.com'),
 (29,'Xyla','Mitchell','mauris@justoPraesent.net'),
 (30,'Dawn','Singleton','Morbi@Aeneanegetmetus.edu'),
 (31,'Fatima','Merrill','eros@vitaevelit.net'),
 (32,'William','Blake','lorem.ac@Maecenas.ca'),
 (33,'Tamara','Mcdowell','blandit@Fusce.net'),
 (34,'Emmanuel','Munoz','gravida@euelitNulla.org'),
 (35,'Baxter','Avila','ornare@arcu.net'),
 (36,'Allen','Hubbard','eu@tempuslorem.ca'),
 (37,'Bradley','Roy','ut.dolor.dapibus@libero.co.uk'),
 (38,'Teegan','Greene','Quisque.tincidunt.pede@metusvitae.co.uk'),
 (39,'Yolanda','Chang','ut@vulputatelacus.net'),
 (40,'Ronan','Blankenship','hendrerit.Donec@dapibusligulaAliquam.co.uk'),
 (41,'Elijah','Bradshaw','neque.pellentesque.massa@lacusUtnec.net'),
 (42,'Kerry','Oneil','morbi@liberoatauctor.ca'),
 (43,'Olga','Wilkerson','dictum.eu.eleifend@Nuncmauriselit.net'),
 (44,'Evangeline','Whitney','est@faucibus.com'),
 (45,'Deirdre','Sanchez','arcu.Nunc.mauris@sem.com'),
 (46,'Nicole','Lamb','Donec.nibh.enim@tinciduntpede.co.uk'),
 (47,'Kalia','Paul','tincidunt.dui@adipiscing.ca'),
 (48,'April','Calderon','dolor.quam@sedpede.net'),
 (49,'Ali','Gutierrez','egestas.Aliquam@nonmassanon.ca'),
 (50,'Emily','Andrews','mi.lorem@cursusvestibulumMauris.co.uk'),
 (51,'Gloria','Blake','lacinia@maurissagittisplacerat.org'),
 (52,'Gil','Adams','in.dolor@neque.net'),
 (53,'Melinda','Willis','semper.pretium@risus.co.uk'),
 (54,'Ciara','Tucker','vitae.sodales@enimMaurisquis.co.uk'),
 (55,'Lee','Mcintyre','non@Pellentesque.ca'),
 (56,'Carly','Cobb','nascetur.ridiculus@orcisemeget.org'),
 (57,'Paki','Yates','in@Etiamlaoreet.edu'),
 (58,'Pascale','Rosa','Curabitur.dictum@SuspendisseduiFusce.com'),
 (59,'Nehru','Cotton','senectus.et@semperrutrum.com'),
 (60,'Kelsie','Miranda','justo.nec@Phasellusataugue.com'),
 (61,'Sawyer','Waters','ultrices.sit@pedeCumsociis.com'),
 (62,'Nevada','Cooley','metus@eteros.ca'),
 (63,'Carissa','Swanson','et@Nullamlobortis.net'),
 (64,'Jasmine','Pitts','massa.Vestibulum.accumsan@facilisis.net'),
 (65,'Tyrone','Mcdonald','ultrices.Vivamus@dui.com'),
 (66,'Lester','Wolf','mauris.Integer@MaurismagnaDuis.co.uk'),
 (67,'James','Dudley','ac@egestasligulaNullam.co.uk'),
 (68,'Philip','Sheppard','ut.sem.Nulla@dignissimmagnaa.edu'),
 (69,'MacKensie','Henson','rutrum@nectellusNunc.co.uk'),
 (70,'Liberty','Bryan','at.fringilla@orci.edu'),
 (71,'Chester','Foreman','elit@elementum.net'),
 (72,'Judith','Lee','erat.vel.pede@egettincidunt.edu'),
 (73,'Wallace','Cotton','nunc.ullamcorper@justofaucibuslectus.edu'),
 (74,'Blake','Wallace','vel.venenatis@cursusluctusipsum.co.uk'),
 (75,'Jaquelyn','Ferguson','eu.odio.tristique@egestasurna.co.uk'),
 (76,'Lila','Whitfield','porttitor.vulputate@necluctus.net'),
 (77,'Stephen','Romero','dolor.Quisque.tincidunt@nulla.net'),
 (78,'Finn','Rhodes','urna@lectussitamet.co.uk'),
 (79,'Reagan','Dawson','enim@Nullatincidunt.edu'),
 (80,'Penelope','Watson','Proin@inceptos.org'),
 (81,'Carl','Kerr','molestie.arcu@ut.edu'),
 (82,'Boris','Hendrix','urna.et@viverraDonec.com'),
 (83,'Eaton','Jensen','est.vitae.sodales@feugiatLoremipsum.com'),
 (84,'Marsden','Oliver','condimentum.Donec@nequeMorbi.edu'),
 (85,'Price','Glenn','a.feugiat@commodoat.edu'),
 (86,'Acton','Hutchinson','Aenean.eget@aliquetodioEtiam.net'),
 (87,'Aquila','Baker','fames.ac.turpis@ultricesaauctor.org'),
 (88,'Kiayada','Hunt','erat@Pellentesquehabitant.com'),
 (89,'Zelenia','Underwood','dignissim.lacus@pulvinararcu.co.uk'),
 (90,'Moana','Sykes','nulla.Integer@MorbimetusVivamus.org'),
 (91,'Oprah','Hansen','vel.convallis.in@etipsumcursus.co.uk'),
 (92,'Chava','Compton','massa.Mauris@nuncinterdum.com'),
 (93,'Bell','Mclean','sit.amet.luctus@dolor.net'),
 (94,'Yasir','Berry','elit.pharetra@risusatfringilla.co.uk'),
 (95,'Juliet','Fields','mollis.non.cursus@arcu.org'),
 (96,'Silas','Arnold','sodales.elit@arcuVestibulumante.co.uk'),
 (97,'Gloria','Harmon','urna.Vivamus@in.co.uk'),
 (98,'Madeline','Soto','elit@Aliquameratvolutpat.net'),
 (99,'Gemma','Gray','laoreet.lectus@diam.net'),
 (100,'Ulric','Lindsay','neque@pedeac.ca');

